name: Deploy Static Content to GitHub Pages

on:
  push:
    branches:
      - main # Trigger workflow setiap kali ada push ke branch 'main'
  workflow_dispatch: # Mengizinkan eksekusi manual dari UI GitHub
  schedule:
    # Setiap hari pada pukul 00:00 UTC (jam 7 pagi WIB)
    - cron: '0 0 * * *'

# Berikan izin yang diperlukan untuk GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Langkah untuk mengatur variabel lingkungan tanggal (sudah kita perbaiki sebelumnya)
      - name: Set date for cache key
        id: date
        run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      # --- PERBAIKAN PENTING: Perbarui path cache ke folder 'dist' ---
      - name: Cache Blogger State and Cache Files
        id: cache-blogger-data
        uses: actions/cache@v4
        with:
          # Mengatur path cache ke folder 'dist'
          path: |
            dist/published_posts.json
            dist/all_blogger_posts_cache.json
          # Menggunakan kunci berdasarkan tanggal untuk memastikan persistensi antar run
          key: ${{ runner.os }}-blogger-data-${{ github.ref }}-${{ env.TODAY }}
          restore-keys: |
            ${{ runner.os }}-blogger-data-${{ github.ref }}-
            ${{ runner.os }}-blogger-data-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy static assets
        run: cp src/static/logo.png dist/ || true

      - name: Run content build script
        env:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python src/build.py

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
